### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by vincentdavis** [flo-compbio/pyaffy#5]
Do you have any tests, or examples with data?
I have data that can be made public is that is a problem.
(I am the guy that asked the 6-year-old StackOverflow question)

**Comment by flo-compbio** [comment]
Hi Vincent,

I uploaded a small [example](https://github.com/flo-compbio/pyaffy-demos/tree/master/minimal) to github ([nbviewer link](http://nbviewer.jupyter.org/github/flo-compbio/pyaffy-demos/blob/master/minimal/01%20-%20Downloading%20the%20data%20and%20running%20pyAffy.ipynb)). Hope that helps.

Please let me know if you have any other comments!

**Comment by vincentdavis** [comment]
That is great, I hope to give this a try on the old data actually. I have some new techniques for analysis I would like to try on the old data.
